services:
  grafrana:
    image: grafana/grafana-enterprise
    container_name: si-12a-grafana
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - observer
    ports:
      - '3000:3000'
  loki:
    image: grafana/loki
    container_name: si-12a-loki
    restart: unless-stopped
    volumes:
      - loki_data:/loki
    networks:
      - observer
  alloy:
    image: grafana/alloy
    container_name: si-12a-alloy
    restart: unless-stopped
    volumes:
      - app_data:/observer_data
    networks:
      - observer
  app:
    image: kea-si-12a
    container_name: si-12a-app
    volumes:
      - app_data:/observer_data

volumes:
  grafana_data:
  loki_data:
  app_data:

networks:
  observer: