services:
  grafrana:
    image: grafana/grafana-enterprise
    container_name: si-12a-grafana
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - observer
    ports:
      - '3000:3000'
  loki:
    image: grafana/loki
    container_name: si-12a-loki
    restart: unless-stopped
    volumes:
      - loki_data:/loki
    networks:
      - observer
  alloy:
    image: grafana/alloy
    container_name: si-12a-alloy
    restart: unless-stopped
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
      - log_data:/observer_data/logs
    networks:
      - observer
    ports:
      - 12345:12345
    command: >
      run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data
      /etc/alloy/config.alloy
  app:
    image: kea-si-12a
    container_name: si-12a-app
    user: hono
    volumes:
      - log_data:/observer_data/logs
    ports:
      - 8080:8080

volumes:
  grafana_data:
  loki_data:
  log_data:

networks:
  observer: